# https://docs.docker.com/compose/compose-file/

services:
  minio:
    image: quay.io/minio/minio:RELEASE.2025-01-20T14-49-07Z
    command:
      - server
      - /data
      - --console-address
      - ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: always

  mealie:
    image: ghcr.io/mealie-recipes/mealie:v2.7.1
    container_name: mealie
    restart: always